<?php

declare(strict_types=1);
require '../includes/security.php';
$admin_id=require_authentication();
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);header('Allow: POST');exit('Method not allowed.');}
verify_csrf();require '../database/db.php';
$s=$con->prepare('SELECT user_type FROM users WHERE user_id=? LIMIT 1');$s->bind_param('i',$admin_id);$s->execute();$admin=$s->get_result()->fetch_assoc();$s->close();if(!$admin||$admin['user_type']!=='Admin'){http_response_code(403);exit('Administrator access required.');}
$report_id=filter_var($_POST['report_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$action=(string)($_POST['action']??'');if(!$report_id||!in_array($action,['dismiss','delete'],true)){http_response_code(422);exit('Invalid moderation request.');}
try{$con->begin_transaction();$s=$con->prepare("SELECT blog_id,status FROM reports WHERE report_id=? FOR UPDATE");$s->bind_param('i',$report_id);$s->execute();$report=$s->get_result()->fetch_assoc();$s->close();if(!$report){throw new RuntimeException('Report not found.');}if($report['status']!=='pending'){throw new RuntimeException('Report has already been reviewed.');}$blog_id=(int)$report['blog_id'];
if($action==='delete'){$s=$con->prepare('SELECT blog_id FROM blogs WHERE blog_id=? LIMIT 1');$s->bind_param('i',$blog_id);$s->execute();$exists=$s->get_result()->num_rows===1;$s->close();if($exists){$s=$con->prepare('DELETE FROM comments WHERE blog_id=?');$s->bind_param('i',$blog_id);$s->execute();$s->close();$s=$con->prepare('DELETE FROM post_likes WHERE blog_id=?');$s->bind_param('i',$blog_id);$s->execute();$s->close();$s=$con->prepare('DELETE FROM blogs WHERE blog_id=?');$s->bind_param('i',$blog_id);$s->execute();$s->close();}$log_action='delete_post';}else{$log_action='dismiss_report';}
$s=$con->prepare("UPDATE reports SET status=?,reviewed_by=?,reviewed_at=NOW() WHERE report_id=?");$status=$action==='delete'?'reviewed':'dismissed';$s->bind_param('sii',$status,$admin_id,$report_id);$s->execute();$s->close();$s=$con->prepare('INSERT INTO moderation_logs(admin_id,report_id,blog_id,action) VALUES(?,?,?,?)');$s->bind_param('iiis',$admin_id,$report_id,$blog_id,$log_action);$s->execute();$s->close();$con->commit();$con->close();header('Location: reports.php');exit;}catch(Throwable $e){$con->rollback();$con->close();error_log('Moderation action failed: '.$e->getMessage());http_response_code($e->getMessage()==='Report not found.'?404:409);exit($e->getMessage()==='Report not found.'?'Report not found.':'Unable to complete moderation action.');}
