<?php

declare(strict_types=1);
require '../includes/security.php';
$user_id=require_authentication();require '../database/db.php';
$blog_id=filter_var($_GET['blog_id']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$blog_id){http_response_code(400);exit('Invalid post.');}
$s=$con->prepare('SELECT blog_id,title,user_id FROM blogs WHERE blog_id=? LIMIT 1');$s->bind_param('i',$blog_id);$s->execute();$blog=$s->get_result()->fetch_assoc();$s->close();if(!$blog){http_response_code(404);exit('Post not found.');}if((int)$blog['user_id']===$user_id){http_response_code(422);exit('You cannot report your own post.');}
$error='';if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$reason=(string)($_POST['reason']??'');$details=trim((string)($_POST['details']??''));$allowed=['spam','harassment','hate or abuse','misinformation','copyright','other'];if(!in_array($reason,$allowed,true))$error='Select a valid reason.';elseif(mb_strlen($details)>2000)$error='Details must be 2000 characters or fewer.';else{$s=$con->prepare("SELECT report_id FROM reports WHERE blog_id=? AND reporter_id=? AND status='pending' LIMIT 1");$s->bind_param('ii',$blog_id,$user_id);$s->execute();$duplicate=$s->get_result()->num_rows===1;$s->close();if($duplicate)$error='You already have a pending report for this post.';else{$s=$con->prepare('INSERT INTO reports(blog_id,reporter_id,reason,details) VALUES(?,?,?,?)');$s->bind_param('iiss',$blog_id,$user_id,$reason,$details);$s->execute();$s->close();$con->close();header('Location: index.php?report=submitted');exit;}}}
function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Report Post | Weblogr</title><link rel="stylesheet" href="style.css"></head><body><?php include 'sidebar.php';?><main class="content"><div class="all-posts-container"><section class="report-card"><p class="eyebrow">COMMUNITY SAFETY</p><h1>Report this post</h1><p>Tell our moderation team what needs attention. Reports are reviewed by administrators.</p><div class="reported-post"><strong><?php echo e((string)$blog['title']);?></strong><span>Post #<?php echo(int)$blog_id;?></span></div><?php if($error):?><div class="form-alert" role="alert"><?php echo e($error);?></div><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?php echo e(csrf_token());?>"><label>Reason<select name="reason" required><option value="">Choose a reason</option><option>spam</option><option>harassment</option><option>hate or abuse</option><option>misinformation</option><option>copyright</option><option>other</option></select></label><label>Additional details<textarea name="details" rows="6" maxlength="2000" placeholder="Add context that can help the moderation team..."></textarea></label><div class="form-actions"><a href="index.php" class="secondary-button">Cancel</a><button class="submit" type="submit">Submit report</button></div></form></section></div></main></body></html>
