<?php

declare(strict_types=1);
require '../includes/security.php';
$user_id=require_authentication();require '../database/db.php';
$s=$con->prepare('SELECT user_type FROM users WHERE user_id=? LIMIT 1');$s->bind_param('i',$user_id);$s->execute();$admin=$s->get_result()->fetch_assoc();$s->close();if(!$admin||$admin['user_type']!=='Admin'){http_response_code(403);exit('Administrator access required.');}
$reports=$con->query("SELECT r.report_id,r.blog_id,r.reason,r.details,r.status,r.created_at,u.username reporter,b.title,a.username author FROM reports r JOIN users u ON u.user_id=r.reporter_id JOIN blogs b ON b.blog_id=r.blog_id JOIN users a ON a.user_id=b.user_id ORDER BY FIELD(r.status,'pending','reviewed','dismissed'),r.created_at DESC");
function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}$csrf=e(csrf_token());
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reports | Weblogr Admin</title><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"></head><body><?php include 'sidebar.php';?><main class="content"><div class="all-posts-container"><header class="feed-header"><p class="eyebrow">MODERATION</p><h1>Report queue</h1><p>Review community reports and record moderation decisions.</p></header><?php if($reports->num_rows):while($row=$reports->fetch_assoc()):?><article class="report-card"><div class="report-heading"><div><span class="report-status status-<?php echo e((string)$row['status']);?>"><?php echo e(ucfirst((string)$row['status']));?></span><h2><?php echo e((string)$row['title']);?></h2><p>Reported by @<?php echo e((string)$row['reporter']);?> · Author @<?php echo e((string)$row['author']);?></p></div><span class="report-date"><?php echo e(date('d M Y H:i',strtotime((string)$row['created_at'])));?></span></div><div class="report-reason"><strong><?php echo e(ucfirst((string)$row['reason']));?></strong><?php if(!empty($row['details'])):?><p><?php echo e((string)$row['details']);?></p><?php endif;?></div><?php if($row['status']==='pending'):?><div class="report-actions"><form method="post" action="moderate_report.php"><input type="hidden" name="csrf_token" value="<?php echo $csrf;?>"><input type="hidden" name="report_id" value="<?php echo(int)$row['report_id'];?>"><input type="hidden" name="action" value="dismiss"><button class="secondary-button" type="submit">Dismiss report</button></form><form method="post" action="moderate_report.php" onsubmit="return confirm('Delete this reported post and resolve the report?');"><input type="hidden" name="csrf_token" value="<?php echo $csrf;?>"><input type="hidden" name="report_id" value="<?php echo(int)$row['report_id'];?>"><input type="hidden" name="action" value="delete"><button class="danger-button" type="submit"><i class="fas fa-trash"></i> Delete post & resolve</button></form></div><?php endif;?></article><?php endwhile;else:?><div class="empty-state"><div class="empty-icon"><i class="fas fa-check-circle"></i></div><h2>All clear</h2><p>There are no community reports to review.</p></div><?php endif;?></div></main></body></html><?php $reports->free();$con->close();?>
